-- Production bank connectivity storage.
-- All access is server-side through the authenticated Cloudflare Worker.
-- Mobile clients receive sanitized connection/account/draft DTOs and never
-- receive provider login identifiers or encrypted credentials.

create extension if not exists pgcrypto;

create table public.bank_connections (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  provider text not null,
  provider_login_ciphertext text,
  provider_login_hash text,
  institution_name text,
  status text not null default 'connecting'
    check (status in ('connecting', 'connected', 'needs_reauth', 'error')),
  sync_cursor text,
  last_sync_at timestamptz,
  last_error_code text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, provider),
  unique (provider, provider_login_hash)
);

create index bank_connections_user_status_idx
  on public.bank_connections (user_id, status);

create table public.bank_connection_sessions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  state_hash text not null unique,
  expires_at timestamptz not null,
  consumed_at timestamptz,
  created_at timestamptz not null default now()
);

create index bank_connection_sessions_active_idx
  on public.bank_connection_sessions (state_hash, expires_at)
  where consumed_at is null;

create table public.bank_accounts (
  id uuid primary key default gen_random_uuid(),
  connection_id uuid not null references public.bank_connections(id) on delete cascade,
  provider_account_id text not null,
  name text not null,
  mask text,
  type text,
  subtype text,
  currency text,
  current_balance numeric(14, 2),
  available_balance numeric(14, 2),
  is_selected boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (connection_id, provider_account_id)
);

create index bank_accounts_connection_selected_idx
  on public.bank_accounts (connection_id, is_selected);

create table public.bank_transaction_imports (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  connection_id uuid not null references public.bank_connections(id) on delete cascade,
  account_id uuid references public.bank_accounts(id) on delete set null,
  provider_transaction_id text not null,
  amount numeric(14, 2) not null check (amount > 0),
  transaction_date date not null,
  transaction_type text not null check (transaction_type in ('expense', 'income')),
  merchant text,
  category_suggestion text,
  note text,
  review_status text not null default 'pending'
    check (review_status in ('pending', 'approved', 'rejected', 'imported')),
  confidence numeric(4, 3) check (confidence between 0 and 1),
  is_pending boolean not null default false,
  raw_hash text not null,
  -- Ledger IDs are generated by the mobile ledger service. This remains a
  -- plain text audit reference so this migration is deployable independently
  -- of the legacy schema bootstrap file.
  ledger_transaction_id text,
  reviewed_at timestamptz,
  imported_at timestamptz,
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (connection_id, provider_transaction_id)
);

create index bank_transaction_imports_review_queue_idx
  on public.bank_transaction_imports (user_id, review_status, transaction_date desc);

create index bank_transaction_imports_account_idx
  on public.bank_transaction_imports (account_id, transaction_date desc);

alter table public.bank_connections enable row level security;
alter table public.bank_connection_sessions enable row level security;
alter table public.bank_accounts enable row level security;
alter table public.bank_transaction_imports enable row level security;

-- These tables intentionally have no anon/authenticated policies. All bank
-- operations go through the Worker, which authenticates a Supabase session and
-- then uses a dedicated server secret. RLS remains enabled as defense in depth.
revoke all on table public.bank_connections from anon, authenticated;
revoke all on table public.bank_connection_sessions from anon, authenticated;
revoke all on table public.bank_accounts from anon, authenticated;
revoke all on table public.bank_transaction_imports from anon, authenticated;

grant select, insert, update, delete on table public.bank_connections to service_role;
grant select, insert, update, delete on table public.bank_connection_sessions to service_role;
grant select, insert, update, delete on table public.bank_accounts to service_role;
grant select, insert, update, delete on table public.bank_transaction_imports to service_role;

create or replace function public.set_bank_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

revoke all on function public.set_bank_updated_at() from public, anon, authenticated;
grant execute on function public.set_bank_updated_at() to service_role;

create trigger bank_connections_set_updated_at
before update on public.bank_connections
for each row execute function public.set_bank_updated_at();

create trigger bank_accounts_set_updated_at
before update on public.bank_accounts
for each row execute function public.set_bank_updated_at();

create trigger bank_transaction_imports_set_updated_at
before update on public.bank_transaction_imports
for each row execute function public.set_bank_updated_at();

comment on column public.bank_connections.provider_login_ciphertext is
  'AES-256-GCM encrypted Flinks loginId. Never returned to clients.';
comment on table public.bank_connection_sessions is
  'Single-use, 15-minute bank callback state records.';
comment on table public.bank_transaction_imports is
  'Durable review queue and import audit records; no raw provider payloads.';
